#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: meson
# autospec version: v7
# autospec commit: f56f1fa
#
Name     : polkit
Version  : 124
Release  : 34
URL      : https://gitlab.freedesktop.org/polkit/polkit/-/archive/124/polkit-124.tar.gz
Source0  : https://gitlab.freedesktop.org/polkit/polkit/-/archive/124/polkit-124.tar.gz
Summary  : PolicyKit Authentication Agent API
Group    : Development/Tools
License  : Apache-2.0 LGPL-2.0
Requires: polkit-bin = %{version}-%{release}
Requires: polkit-config = %{version}-%{release}
Requires: polkit-data = %{version}-%{release}
Requires: polkit-lib = %{version}-%{release}
Requires: polkit-license = %{version}-%{release}
Requires: polkit-locales = %{version}-%{release}
Requires: polkit-services = %{version}-%{release}
Requires: polkit-setuid = %{version}-%{release}
BuildRequires : Linux-PAM-dev
BuildRequires : buildreq-meson
BuildRequires : expat-dev
BuildRequires : intltool-dev
BuildRequires : pkgconfig(dbus-python)
BuildRequires : pkgconfig(duktape)
BuildRequires : pkgconfig(gobject-introspection-1.0)
BuildRequires : pkgconfig(libsystemd)
BuildRequires : pypi-python_dbusmock
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0002-pkexec-Support-a-stateless-configuration.patch
Patch2: 0003-Don-t-complain-about-etc-polkit-2-rules.d-missing.patch
Patch3: 0004-Support-os_type-of-ClearLinux.patch
Patch4: more-gc.patch

%description
OVERVIEW
========
polkit is a toolkit for defining and handling authorizations.  It is
used for allowing unprivileged processes to speak to privileged
processes.

%package bin
Summary: bin components for the polkit package.
Group: Binaries
Requires: polkit-data = %{version}-%{release}
Requires: polkit-config = %{version}-%{release}
Requires: polkit-setuid = %{version}-%{release}
Requires: polkit-license = %{version}-%{release}
Requires: polkit-services = %{version}-%{release}

%description bin
bin components for the polkit package.


%package config
Summary: config components for the polkit package.
Group: Default

%description config
config components for the polkit package.


%package data
Summary: data components for the polkit package.
Group: Data

%description data
data components for the polkit package.


%package dev
Summary: dev components for the polkit package.
Group: Development
Requires: polkit-lib = %{version}-%{release}
Requires: polkit-bin = %{version}-%{release}
Requires: polkit-data = %{version}-%{release}
Provides: polkit-devel = %{version}-%{release}
Requires: polkit = %{version}-%{release}

%description dev
dev components for the polkit package.


%package lib
Summary: lib components for the polkit package.
Group: Libraries
Requires: polkit-data = %{version}-%{release}
Requires: polkit-license = %{version}-%{release}

%description lib
lib components for the polkit package.


%package license
Summary: license components for the polkit package.
Group: Default

%description license
license components for the polkit package.


%package locales
Summary: locales components for the polkit package.
Group: Default

%description locales
locales components for the polkit package.


%package services
Summary: services components for the polkit package.
Group: Systemd services
Requires: systemd

%description services
services components for the polkit package.


%package setuid
Summary: setuid components for the polkit package.
Group: Default

%description setuid
setuid components for the polkit package.


%prep
%setup -q -n polkit-124
cd %{_builddir}/polkit-124
%patch -P 1 -p1
%patch -P 2 -p1
%patch -P 3 -p1
%patch -P 4 -p1
pushd ..
cp -a polkit-124 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1712620845
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
meson --libdir=lib64 --prefix=/usr --buildtype=plain -Dgtk_doc=false \
-Dman=false \
-Dsession_tracking=libsystemd-login \
-Dos_type=ClearLinux \
-Dexamples=true  builddir
ninja -v -C builddir
GOAMD64=v3
CFLAGS="$CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 " CXXFLAGS="$CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 " LDFLAGS="$LDFLAGS -march=x86-64-v3 " meson --libdir=lib64 --prefix=/usr --buildtype=plain -Dgtk_doc=false \
-Dman=false \
-Dsession_tracking=libsystemd-login \
-Dos_type=ClearLinux \
-Dexamples=true  builddiravx2
ninja -v -C builddiravx2

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
meson test -C builddir --print-errorlogs

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
mkdir -p %{buildroot}/usr/share/package-licenses/polkit
cp %{_builddir}/polkit-%{version}/COPYING %{buildroot}/usr/share/package-licenses/polkit/d83b6378d06fdf228b1afc0bf97e09b44bbb2e7b || :
cp %{_builddir}/polkit-%{version}/test/mocklibc/COPYING %{buildroot}/usr/share/package-licenses/polkit/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
GOAMD64=v3
DESTDIR=%{buildroot}-v3 ninja -C builddiravx2 install
GOAMD64=v2
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang polkit-1
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name} --skip-path /usr/bin/pkexec --skip-path /usr/lib/polkit-1/polkit-agent-helper-1

%files
%defattr(-,root,root,-)
/V3/usr/lib/polkit-1/polkitd
/usr/lib/pam.d/polkit-1
/usr/lib/polkit-1/polkitd

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/pk-example-frobnicate
/V3/usr/bin/pkaction
/V3/usr/bin/pkcheck
/V3/usr/bin/pkttyagent
/usr/bin/pk-example-frobnicate
/usr/bin/pkaction
/usr/bin/pkcheck
/usr/bin/pkttyagent

%files config
%defattr(-,root,root,-)
/usr/lib/sysusers.d/polkit.conf

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/Polkit-1.0.typelib
/usr/lib64/girepository-1.0/PolkitAgent-1.0.typelib
/usr/share/dbus-1/system-services/org.freedesktop.PolicyKit1.service
/usr/share/dbus-1/system.d/org.freedesktop.PolicyKit1.conf
/usr/share/gettext/its/polkit.its
/usr/share/gettext/its/polkit.loc
/usr/share/gir-1.0/*.gir
/usr/share/polkit-1/actions/org.freedesktop.policykit.examples.pkexec.policy
/usr/share/polkit-1/actions/org.freedesktop.policykit.policy
/usr/share/polkit-1/policyconfig-1.dtd
/usr/share/polkit-1/rules.d/50-default.rules

%files dev
%defattr(-,root,root,-)
/usr/include/polkit-1/polkit/polkit.h
/usr/include/polkit-1/polkit/polkitactiondescription.h
/usr/include/polkit-1/polkit/polkitauthority.h
/usr/include/polkit-1/polkit/polkitauthorityfeatures.h
/usr/include/polkit-1/polkit/polkitauthorizationresult.h
/usr/include/polkit-1/polkit/polkitcheckauthorizationflags.h
/usr/include/polkit-1/polkit/polkitdetails.h
/usr/include/polkit-1/polkit/polkitenumtypes.h
/usr/include/polkit-1/polkit/polkiterror.h
/usr/include/polkit-1/polkit/polkitidentity.h
/usr/include/polkit-1/polkit/polkitimplicitauthorization.h
/usr/include/polkit-1/polkit/polkitpermission.h
/usr/include/polkit-1/polkit/polkitprivate.h
/usr/include/polkit-1/polkit/polkitsubject.h
/usr/include/polkit-1/polkit/polkitsystembusname.h
/usr/include/polkit-1/polkit/polkittemporaryauthorization.h
/usr/include/polkit-1/polkit/polkittypes.h
/usr/include/polkit-1/polkit/polkitunixgroup.h
/usr/include/polkit-1/polkit/polkitunixnetgroup.h
/usr/include/polkit-1/polkit/polkitunixprocess.h
/usr/include/polkit-1/polkit/polkitunixsession.h
/usr/include/polkit-1/polkit/polkitunixuser.h
/usr/include/polkit-1/polkitagent/polkitagent.h
/usr/include/polkit-1/polkitagent/polkitagentenumtypes.h
/usr/include/polkit-1/polkitagent/polkitagentlistener.h
/usr/include/polkit-1/polkitagent/polkitagentsession.h
/usr/include/polkit-1/polkitagent/polkitagenttextlistener.h
/usr/include/polkit-1/polkitagent/polkitagenttypes.h
/usr/lib64/libpolkit-agent-1.so
/usr/lib64/libpolkit-gobject-1.so
/usr/lib64/pkgconfig/polkit-agent-1.pc
/usr/lib64/pkgconfig/polkit-gobject-1.pc

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libpolkit-agent-1.so.0.0.0
/V3/usr/lib64/libpolkit-gobject-1.so.0.0.0
/usr/lib64/libpolkit-agent-1.so.0
/usr/lib64/libpolkit-agent-1.so.0.0.0
/usr/lib64/libpolkit-gobject-1.so.0
/usr/lib64/libpolkit-gobject-1.so.0.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/polkit/2b8b815229aa8a61e483fb4ba0588b8b6c491890
/usr/share/package-licenses/polkit/d83b6378d06fdf228b1afc0bf97e09b44bbb2e7b

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/polkit.service

%files setuid
%defattr(-,root,root,-)
%attr(4755, root, root) /usr/bin/pkexec
%attr(4755, root, root) /usr/lib/polkit-1/polkit-agent-helper-1

%files locales -f polkit-1.lang
%defattr(-,root,root,-)

